name: hvh

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: hvh-postgres-postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: hvh-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#  postgres:
#    image: postgres:16
#    container_name: hvh-postgres
#    restart: unless-stopped
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: hvh-db
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


volumes:
  postgres_data:
  rabbitmq_data: