package com.sep490.g28.hvh.be.constant;

public enum ENotificationType {
    //EVENT
    MNG_EVENT_CREATED, //sent to mng, event created by host

    HOST_EVENT_CREATE_APPROVED_BY_MNG, //send to host
    ADM_EVENT_CREATE_APPROVED_BY_MNG, //send to admin

    HOST_EVENT_CREATE_REJECTED_BY_MNG, //send to host only

    HOST_EVENT_CREATE_APPROVED_BY_ADM, //send to host
    MNG_EVENT_CREATE_APPROVED_BY_ADM, //send to mng

    HOST_EVENT_CREATE_REJECTED_BY_ADM, //send to host
    MNG_EVENT_CREATE_REJECTED_BY_ADM, //send to manager

    MNG_EVENT_UPDATED_BY_HOST,

    HOST_EVENT_UPDATE_NON_CRITICAL_APPROVED_BY_MNG,
    VOL_EVENT_UPDATE_NON_CRITICAL_APPROVED_BY_MNG,

    HOST_EVENT_UPDATE_CRITICAL_APPROVED_BY_MNG,

    HOST_EVENT_UPDATE_REJECTED_BY_MNG,

    HOST_EVENT_UPDATE_CRITICAL_APPROVED_BY_ADM,
    MNG_EVENT_UPDATE_CRITICAL_APPROVED_BY_ADM,
    VOL_EVENT_UPDATE_CRITICAL_APPROVED_BY_ADM,

    HOST_EVENT_UPDATE_CRITICAL_REJECTED_BY_ADM,
    MNG_EVENT_UPDATE_CRITICAL_REJECTED_BY_ADM,

    VOL_APPLICATION_APPROVED, //send to vol
    VOL_APPLICATION_REJECTED, //send to vol
    VOL_APPLICATION_CANCELLED, //send to vol

    VOL_EVENT_ANNOUNCEMENT,
    VOL_EVENT_CANCELLED_BY_HOST,
    VOL_EVENT_CANCELLED_BY_AD,
}
