front-end.web.base-urls=${FE_WEB_BASE_URLS}
front-end.web.cert-url=${FE_WEB_CERT_URL}

spring.datasource.url=${DB_URL}

firebase.credentials-path=${FIREBASE_SA_KEY_PATH}
#====================================
#enable flyway
spring.flyway.enabled=true

#====================================
#supabase
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SP_JWT_ISSUER_URI}

supabase.url=${SP_URL}
supabase.api-secret-key=${SP_API_SECRET_KEY}
supabase.bucket=${SP_BUCKET_NAME}

#====================================
#mail trap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAILTRAP_USERNAME}
spring.mail.password=${MAILTRAP_PASSWORD}

#====================================
spring.rabbitmq.addresses=${RBMQ_AMQP_URL}

#====================================
#redis
spring.data.redis.host=${RD_HOST}
spring.data.redis.port=${RD_PORT}
spring.data.redis.password=${RD_PASSWORD}

#====================================
face-authen.api.base-url=${FACEAUTHEN_API_BASE_URL}

# database connection pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.initialization-fail-timeout=0