spring.datasource.url=jdbc:postgresql://localhost:5432/hvh-db
spring.datasource.username=postgres
spring.datasource.password=password

#====================================
#enable flyway
spring.flyway.enabled=true

#====================================
#faceapi
face-authen.api.base-url=${FACEAUTHEN_API_BASE_URL}