spring.datasource.url=jdbc:postgresql://localhost:5432/hvh-db
spring.datasource.username=postgres
spring.datasource.password=password

#====================================
#enable flyway
spring.flyway.enabled=true

#faceapi
api.base-url=http://34.142.251.160