spring.application.name=HVH-BE

# API return VN
spring.jackson.time-zone=Asia/Ho_Chi_Minh

front-end.web.baseUrl=http://localhost:3000

firebase.credentials-path=./serviceAccountKey.json

#spring.datasource.url=${DB_URL}
#spring.datasource.url=jdbc:postgresql://localhost:5432/hvh-db
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#====================================
#enable flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration

#====================================
#hibernate just check schema (map)
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

spring.data.redis.repositories.enabled=false

#====================================
#upload file size limit
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB

#====================================
#supabase
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SP_JWT_ISSUER_URI}

supabase.url=${SP_URL}
supabase.api-secret-key=${SP_API_SECRET_KEY}
supabase.bucket=${SP_BUCKET_NAME}

#====================================
#springdoc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#====================================
#mail
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${EMAIL_USERNAME}
#spring.mail.password=${EMAIL_PASSWORD}

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAILTRAP_USERNAME}
spring.mail.password=${MAILTRAP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#====================================
#rabbitMQ
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=${RBMQ_USERNAME}
#spring.rabbitmq.password=${RBMQ_PASSWORD}
#spring.rabbitmq.virtual-host=/
#spring.rabbitmq.listener.simple.acknowledge-mode=auto
#spring.rabbitmq.listener.simple.default-requeue-rejected=false

spring.rabbitmq.addresses=${RBMQ_AMQP_URL}
#--------------------------
rabbitmq.email.exchange=email.exchange

rabbitmq.email.queue.send=email.queue.send
rabbitmq.email.queue.retry=email.queue.retry
rabbitmq.email.queue.dlq=email.queue.dlq

rabbitmq.email.routing.send=email.routing.send
rabbitmq.email.routing.retry=email.routing.retry
rabbitmq.email.routing.dlq=email.routing.dlq
#30s
rabbitmq.email.retry.ttl=30000
rabbitmq.email.retry.max-attempts=3
#--------------------------
rabbitmq.notification.exchange=notification.exchange

rabbitmq.notification.queue.send-user=notification.queue.send.user
rabbitmq.notification.queue.send-topic=notification.queue.send.topic
rabbitmq.notification.queue.retry-user=notification.queue.retry.user
rabbitmq.notification.queue.retry-topic=notification.queue.retry.topic
rabbitmq.notification.queue.dlq-user=notification.queue.dlq.user
rabbitmq.notification.queue.dlq-topic=notification.queue.dlq.topic

rabbitmq.notification.routing.send-user=notification.routing.send.user
rabbitmq.notification.routing.send-topic=notification.routing.send.topic
rabbitmq.notification.routing.retry-user=notification.routing.retry.user
rabbitmq.notification.routing.retry-topic=notification.routing.retry.topic
rabbitmq.notification.routing.dlq-user=notification.routing.dlq.user
rabbitmq.notification.routing.dlq-topic=notification.routing.dlq.topic

rabbitmq.notification.queue.subscribe=notification.queue.subscribe
rabbitmq.notification.queue.subscribe-retry=notification.queue.subscribe.retry
rabbitmq.notification.queue.subscribe-dlq=notification.queue.subscribe.dlq

rabbitmq.notification.routing.subscribe=notification.routing.subscribe
rabbitmq.notification.routing.subscribe-retry=notification.routing.subscribe.retry
rabbitmq.notification.routing.subscribe-dlq=notification.routing.subscribe.dlq

rabbitmq.notification.queue.unsubscribe=notification.queue.unsubscribe
rabbitmq.notification.queue.unsubscribe-retry=notification.queue.unsubscribe.retry
rabbitmq.notification.queue.unsubscribe-dlq=notification.queue.unsubscribe.dlq

rabbitmq.notification.routing.unsubscribe=notification.routing.unsubscribe
rabbitmq.notification.routing.unsubscribe-retry=notification.routing.unsubscribe.retry
rabbitmq.notification.routing.unsubscribe-dlq=notification.routing.unsubscribe.dlq

#1m
rabbitmq.notification.retry.ttl=60000
rabbitmq.notification.retry.max-attempts=3

#====================================
#redis
spring.data.redis.host=${RD_HOST}
spring.data.redis.port=${RD_PORT}
spring.data.redis.password=${RD_PASSWORD}

#====================================
# database connection pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.initialization-fail-timeout=0